language: python
services:
- docker
env:
  global:
    - AWS_DEFAULT_REGION='ap-northeast-1'
    - ECR_REPO='workshop-aws-ecs-with-cicd'
    - ECR_IMAGE_TAG='alpha'
    - ECS_CLUSTER_NAME='workshop-ecs'
    - ECS_SERIVCE_NAME='workshop-ecs-service'
install:
  - echo "install nothing!"
script:
  - echo "not tests!"
after_success:
  - echo "travis build version: $TRAVIS_BUILD_NUMBER" > src/version.txt
deploy:
  provider: script
  # specify the deployment script
  script: bash scripts/deploy.sh